% Dobashi implementation
%
%
%
%
%
%

function Table = Construct_Table(n) 

global Table

% Read-in spec for how many orientation and inflow speed we want to do. 
% Table is a class. Each object in the class records the simulation description of a unique point in the simulation parameter space. 
%
% in the class is generated by reading the SimSpec description.

%
%
load('./SimSpec_files/simulation_spec.mat');

LenTable  = length(Table);
NumSource = 10;

for ii = 1:LenTable 
    Table(ii).Texture = Compute_Texture(ii, NumSource); 
end



end



%%%%%%%%

function Compute_Texture(ii, NumSource)

global Table

[T,D1,D2,D3] = Read_Simulation(Table(ii).files); 
Discretize_Object(NumSource);

% Process the data differently depending on the software used
%
% OpenFoam:  
% ---------
%
%   File name: forcesProcessed_matlab.mat
%
%   T   Forces_X    Forces_Y    Forces_Z
%   ------------------------------------
%
%

switch SimSpec_ii.software
    case {'OpenFoam', 'Openfoam', 'OpenFOAM'}
        disp('Simulation done by OpenFoam.')
                
    case 'Fluent'
        disp('Simulation done by ANSYS Fluent.')'
    otherwise 
        disp('Simulation software not recognized!')
end







